var res = {
    HelloWorld_png : "res/HelloWorld.png",
    CloseNormal_png : "res/CloseNormal.png",
    CloseSelected_png : "res/CloseSelected.png",
    boton_nivel_1: "res/nivel_1.png",
    boton_nivel_2: "res/nivel_2.png",
    menu_titulo_png : "res/menu_titulo.png",
    mapa1_tmx: "res/mapa1.tmx",
    tiles32_png: "res/tiles32.png",
    glass11: "res/glass11.png",
    glass12: "res/glass12.png",
    glass13: "res/glass13.png",
    glass21: "res/glass21.png",
    glass22: "res/glass22.png",
    glass23: "res/glass23.png",
    wood11: "res/wood11.png",
    wood12: "res/wood12.png",
    wood13: "res/wood13.png",
    wood21: "res/wood21.png",
    wood22: "res/wood22.png",
    wood23: "res/wood23.png",
    stone11: "res/stone11.png",
    stone12: "res/stone12.png",
    stone13: "res/stone13.png",
    stone21: "res/stone21.png",
    stone22: "res/stone22.png",
    stone23: "res/stone23.png",
    sling1: "res/sling1.png",
    sling2: "res/sling2.png",
    sling3: "res/sling3.png",
    pelota: "res/pelota.png",
    pelota_multiple: "res/pelota_multiple.png",
    mini_proyectil: "res/mini_proyectil.png",
    proyectil_ovni: "res/proyectil_ovni.png",
    disparo_ovni: "res/disparo_ovni.png",
    alienBeige_round: "res/alienBeige_round.png",
    alienBlue_round: "res/alienBlue_round.png",
    alienGreen_round: "res/alienGreen_round.png",
    alienPink_round: "res/alienPink_round.png",
    alienYellow_round: "res/alienYellow_round.png",
    alienBeige_square: "res/alienBeige_square.png",
    alienBlue_square: "res/alienBlue_square.png",
    alienGreen_square: "res/alienGreen_square.png",
    alienPink_square: "res/alienPink_square.png",
    alienYellow_square: "res/alienYellow_square.png",
    alienBeige_suit: "res/alienBeige_suit.png",
    alienBlue_suit: "res/alienBlue_suit.png",
    alienGreen_suit: "res/alienGreen_suit.png",
    alienPink_suit: "res/alienPink_suit.png",
    alienYellow_suit: "res/alienYellow_suit.png"
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}